"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SocketEvents = void 0;
var SocketEvents;
(function (SocketEvents) {
    SocketEvents["JoinRoom"] = "joinRoom";
    SocketEvents["RoomJoined"] = "roomJoined";
    SocketEvents["LeaveRoom"] = "leaveRoom";
    SocketEvents["RoomLeft"] = "roomLeft";
    SocketEvents["MarkReady"] = "markReady";
    SocketEvents["playerReady"] = "playerReady";
    SocketEvents["StartGame"] = "startGame";
    SocketEvents["SendMessage"] = "sendMessage";
    SocketEvents["MessageSent"] = "messageSent";
    SocketEvents["GameUpdate"] = "gameUpdate";
    SocketEvents["PlayerUpdate"] = "playerUpdate";
    SocketEvents["PlayCard"] = "playCard";
    SocketEvents["GetMe"] = "getMe";
    SocketEvents["SelectBestCard"] = "selectBestCard";
    SocketEvents["SelectNomination"] = "selectNomination";
    SocketEvents["PickUp"] = "pickUp";
    SocketEvents["PlayerWon"] = "playerWon";
})(SocketEvents = exports.SocketEvents || (exports.SocketEvents = {}));
